version: 2
general:
  artifacts:
    - "npm-debug.log"
jobs:
  build:
    working_directory: ~/busy
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: code-coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
